# 通用CMS配置文件

app:
  host: ":8085"
  debug: false
  baseurl: "http://127.0.0.1:8085"
  language: "es"
  s3url: "https://pre-europe.s3.eu-central-1.amazonaws.com/es-comic/img40/"

mysql:
  dsn: "root:123456@(127.0.0.1:3306)/pre_cartoon3?charset=utf8"

redis:
  maxidle: 50 # 连接池中最大空闲连接数量
  max_active: 30 # 最大连接数量
  idle_timeout: 300 # 最大超时时间(s)
  port: "127.0.0.1:6379"
